### ISSUE TITLE
[Logging, Health Checks] kibana nem indul a laborgépeken

### ISSUE THREAD

**Issue by june9666** [bmeviauav42/todoapp-logging-hc#7]
Kibanát nem lehet elérni az alapbeállításokkal, laboron.

Solution: Kicsit fel kell skálázni a vasat alatta. (pontos értékeket majd meg kell nézni)

![image](https://user-images.githubusercontent.com/37378045/69723676-794af980-111a-11ea-96d3-6b98e0ace721.png)

**Comment by totht91** [comment]
@june9666 Köszönöm! Érdekes, hogy az én gépemen az alapbeállításokkal is ment. Ettől függetlenül utána fogok nézni mi volt a gond a laboron.

![image](https://user-images.githubusercontent.com/8333960/69756745-80dec280-115b-11ea-93f9-0aeee74f91a8.png)

**Comment by tibitoth** [comment]
nem tartjuk már a tárgyat
